debug: false

spring:
  application:
    name: Cookbook
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cookbook
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PWD}

server:
  port: 8080